name: redeploy 
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@@master

      - name: buildAndDeploy
        uses: JamesIves/github-pages-deploy-action@@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKENS }}
          BRANCH: main #存放产物分支名称
          FOLDER: dist # 存放build后的目录
          BUILD_SCRIPT: npm install && npm run build #执行的命令
