name: redeploy 
on: push
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: buildAndDeploy
        uses: JamesIves/github-pages-deploy-action@releases/v2
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKENS }}
          BRANCH: gh-pages #存放产物分支名称
          FOLDER: dist # 存放build后的目录
          BUILD_SCRIPT: npm install && npm run build #执行的命令
